import { ScheduleData, Member, Role } from '@/types';

// 参加メンバー
export const members: Member[] = [
  { id: 'okabe-1', name: '岡部 夫', family: 'okabe' },
  { id: 'okabe-2', name: '岡部 妻', family: 'okabe' },
  { id: 'ito-1', name: '伊藤 夫', family: 'ito' },
  { id: 'ito-2', name: '伊藤 妻', family: 'ito' },
  { id: 'imai-1', name: '今井 夫', family: 'imai' },
  { id: 'imai-2', name: '今井 妻', family: 'imai' },
  { id: 'ono-1', name: '小野 夫', family: 'ono' },
  { id: 'ono-2', name: '小野 妻', family: 'ono' },
];

// 旅の目的
export const purposes: string[] = [
  '奄美大島の自然を存分に満喫する',
  '今回は全員海中の自然を楽しむのでウミガメに出会えることを祈る 🐢',
  'このメンバーであと何回行けるかわからない旅行をかみしめる',
];

// 注意事項
export const notices: string[] = [
  '各自健康には十分注意し、任意ではありますが帯状疱疹・インフルエンザの予防注射は打っておく',
  '大島のように不測の事態も想定し下着は余分に持っていく',
  'このしおりには本音とジョークが混ざっているのでしっかり判断する',
  '絶対に喧嘩をしない',
];

// 係り分担
export const roles: Role[] = [
  {
    id: 'role-1',
    name: '班長',
    member: '小野 夫',
    description: '全体をまとめ、楽しい旅行となるよう配慮する。しっかり責任は取る。班長が道やルートを間違えたらコッソリ文句を言う',
  },
  {
    id: 'role-2',
    name: '風紀係',
    member: '伊藤 夫',
    description: '最も重要な係、全体が羽目を外さないよう又途中で寝ないよう見張る。助手席は絶対に寝ないように指導',
  },
  {
    id: 'role-3',
    name: '宴会係',
    member: '岡部 夫',
    description: '主に宴会時の飲み物つまみを確保。自分は飲まないからと言って手を抜かない。当然2日間やる気合いを見せる',
  },
  {
    id: 'role-4',
    name: 'YouTube係',
    member: '小野 妻',
    description: '事前にYouTubeをよく見ておき有益な情報をGetする',
  },
  {
    id: 'role-5',
    name: '会計係',
    member: '岡部 妻',
    description: '毎回費用を記録し、公正に努める。間違っても岡部家に有利にしてはいけない。勿論PayPayが自在に使えるよう',
  },
  {
    id: 'role-6',
    name: '食事係',
    member: '今井 妻',
    description: '各食事の時間、場所の確認。遅れたり間違えた参加者には厳しく指導。勿論残さず食べさせる',
  },
  {
    id: 'role-7',
    name: 'お助け係',
    member: '伊藤 妻',
    description: 'いわゆる各係の仕事を監視し、大変な所をサポートする',
  },
  {
    id: 'role-8',
    name: '副班長',
    member: '今井 夫',
    description: '固定になってしまいますがよろしくお願いいたします',
  },
];

// 日程データ（初期データ）
export const initialScheduleData: ScheduleData = {
  schedule: [
    {
      date: '2024-11-03',
      dateLabel: '11月3日（月曜日）',
      items: [
        {
          id: 'item-1',
          time: '6:30',
          activity: '羽田第1ターミナル第3時計台に集合',
          note: '朝食は各自用意をしておく、帰りのチケットを配布',
          checked: false,
          location: {
            name: '羽田空港第1ターミナル',
            lat: 35.5494,
            lng: 139.7798,
            address: '東京都大田区羽田空港',
          },
          website: 'https://tokyo-haneda.com/floor/terminal1/index.html',
          type: 'sightseeing',
        },
        {
          id: 'item-2',
          time: '7:30',
          activity: '離陸 JAL103便（羽田→伊丹）',
          note: 'JAL103便 7:50→8:40',
          checked: false,
          location: {
            name: '羽田空港',
            lat: 35.5494,
            lng: 139.7798,
            address: '東京都大田区羽田空港',
          },
          website: 'https://tokyo-haneda.com/floor/terminal1/index.html',
          type: 'sightseeing',
        },
        {
          id: 'item-3',
          time: '8:40',
          activity: '大阪伊丹空港着',
          note: 'JAL103便（羽田→伊丹）7:50→8:40',
          checked: false,
          location: {
            name: '大阪国際空港（伊丹空港）',
            lat: 34.7855,
            lng: 135.4382,
            address: '大阪府豊中市',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-4',
          time: '9:55',
          activity: '大阪伊丹空港発',
          note: 'JAL2465便（伊丹→奄美大島）9:55→11:40',
          checked: false,
          location: {
            name: '大阪国際空港（伊丹空港）',
            lat: 34.7855,
            lng: 135.4382,
            address: '大阪府豊中市',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-5',
          time: '11:55',
          activity: '奄美大島空港着',
          note: 'JAL2465便（伊丹→奄美大島）9:55→11:40',
          checked: false,
          location: {
            name: '奄美大島空港',
            lat: 28.4306,
            lng: 129.7128,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-6',
          time: '12:30',
          activity: 'レンタカー乗車',
          note: '10人乗りなのでゆったりです',
          checked: false,
          location: {
            name: '奄美大島空港',
            lat: 28.4306,
            lng: 129.7128,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'activity',
        },
        {
          id: 'item-7',
          time: '13:00',
          activity: '昼食 海工房（海を見ながら）',
          note: '',
          checked: false,
          location: {
            name: '海工房(イタリアン)',
            lat: 28.403687878222275,
            lng: 129.64599138674743,
            address: '鹿児島県大島郡瀬戸内町',
          },
          website: 'https://kyoraumi.com/',
          type: 'restaurant',
        },
        {
          id: 'item-8',
          time: '13:30',
          activity: 'シュノーケリング ネイティブシティ奄美',
          note: '',
          checked: false,
          location: {
            name: 'ネイティブシティ奄美',
            lat: 28.428814095762462,
            lng: 129.6193030356203,
            address: '鹿児島県奄美市',
          },
          website: 'https://amami-diving.com/',
          type: 'activity',
        },
        {
          id: 'item-9',
          time: '15:30',
          activity: '終了 ハートロックへ',
          note: '',
          checked: false,
          location: {
            name: 'ハートロック',
            lat: 28.4069412006226,
            lng: 129.6285008107394,
            address: '鹿児島県奄美市',
          },
          website: 'https://www.arukikata.co.jp/tokuhain/261380/',
          type: 'sightseeing',
        },
        {
          id: 'item-10',
          time: '17:30',
          activity: 'オンシェアー サンセットクルーズ',
          note: '',
          checked: false,
          location: {
            name: 'オンシェアー',
            lat: 28.419906600951478,
            lng: 129.619939996122,
            address: '鹿児島県奄美市',
          },
          website: 'https://www.amamionshore.com/shimauta-sunset',
          type: 'activity',
        },
        {
          id: 'item-11',
          time: '19:00',
          activity: '終了 ホテルカレッタへ',
          note: '',
          checked: false,
          location: {
            name: 'ホテルカレッタ',
            lat: 28.4292, 
            lng: 129.6160,
            address: '鹿児島県大島郡龍郷町芦徳419-1',
          },
          type: 'hotel',
        },
        {
          id: 'item-12',
          time: '19:30',
          activity: 'チェックイン',
          note: '0997-62-3821 鹿児島県大島郡龍郷町芦徳419-1',
          checked: false,
          location: {
            name: 'ホテルカレッタ',
            lat: 28.4292, 
            lng: 129.6160,
            address: '鹿児島県大島郡龍郷町芦徳419-1',
          },
          type: 'hotel',
        },
        {
          id: 'item-13',
          time: '20:00',
          activity: '外食 近くの鳥料理店？',
          note: '',
          checked: false,
          location: {
            name: 'ホテルカレッタ周辺',
            lat: 28.4292, 
            lng: 129.6160,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'restaurant',
        },
      ],
    },
    {
      date: '2024-11-04',
      dateLabel: '11月4日（火曜日）',
      items: [
        {
          id: 'item-14',
          time: '7:30',
          activity: '朝食',
          note: 'そのまま出発出来るように準備',
          checked: false,
          location: {
            name: 'ホテルカレッタ',
            lat: 28.4292, 
            lng: 129.6160,
            address: '鹿児島県大島郡龍郷町芦徳419-1',
          },
          type: 'restaurant',
        },
        {
          id: 'item-15',
          time: '8:00',
          activity: 'ホテル出発<br>観光 名瀬方面ドライブ',
          note: '',
          checked: false,
          location: {
            name: '名瀬方面',
            lat: 28.3764,
            lng: 129.4936,
            address: '鹿児島県奄美市',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-16',
          time: '9:30',
          activity: '金作原原生林ツアー 2時間',
          note: '',
          checked: false,
          location: {
            name: '金作原原生林',
            lat: 28.345750724935893,
            lng: 129.4479469800486,
            address: '鹿児島県奄美市',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-17',
          time: '12:00',
          activity: '鶏飯 ひさ倉',
          note: '',
          checked: false,
          location: {
            name: '鶏飯 ひさ倉',
            lat: 28.414477784633608,
            lng: 129.60165744448688,
            address: '鹿児島県奄美市',
          },
          website: 'https://hisakura.synapse-site.jp/',
          type: 'restaurant',
        },
        {
          id: 'item-18',
          time: '13:15',
          activity: '大浜海浜公園か奄美博物館',
          note: '',
          checked: false,
          location: {
            name: '大浜海浜公園',
            lat: 28.40418138573366,
            lng: 129.45492310280687,
            address: '鹿児島県奄美市',
          },
          website: 'https://www.ohama.marutani-amami.com/ocean-exhibition-hall',
          type: 'sightseeing',
        },
        {
          id: 'item-19',
          time: '15:00',
          activity: 'ホテルウエストコート本館チェックイン',
          note: '0977-52-8080',
          checked: false,
          location: {
            name: 'ホテルウエストコート本館',
            lat: 28.382888451824773,
            lng: 129.4938885136643,
            address: '鹿児島県奄美市',
          },
          website: 'https://www.westcourt.co.jp/',
          type: 'hotel',
        },
        {
          id: 'item-20',
          time: '15:20',
          activity: 'マングローブパークへ',
          note: '',
          checked: false,
          location: {
            name: 'マングローブパーク',
            lat: 28.259748875769795,
            lng: 129.4087869702612,
            address: '鹿児島県奄美市',
          },
          website: 'https://www.mangrovepark.com/',
          type: 'sightseeing',
        },
        {
          id: 'item-21',
          time: '16:00',
          activity: 'サンセットマングローブツアーと黒兎探検ツアー',
          note: '',
          checked: false,
          location: {
            name: 'マングローブパーク',
            lat: 28.259748875769795,
            lng: 129.4087869702612,
            address: '鹿児島県奄美市',
          },
          type: 'activity',
        },
        {
          id: 'item-22',
          time: '19:30',
          activity: '終了',
          note: '',
          checked: false,
          location: {
            name: 'マングローブパーク',
            lat: 28.259748875769795,
            lng: 129.4087869702612,
            address: '鹿児島県奄美市',
          },
          type: 'activity',
        },
        {
          id: 'item-23',
          time: '20:00',
          activity: '夕食 どこか予約するか居酒屋みたいなところに飛び込みか',
          note: '',
          checked: false,
          location: {
            name: 'ホテルウエストコート周辺',
            lat: 28.382888451824773,
            lng: 129.4938885136643,
            address: '鹿児島県奄美市',
          },
          type: 'restaurant',
        },
      ],
    },
    {
      date: '2024-11-05',
      dateLabel: '11月5日（水曜日）',
      items: [
        {
          id: 'item-24',
          time: '8:00',
          activity: '朝食',
          note: 'そのまま出発出来るように準備（疲れているのでちょっと遅く）',
          checked: false,
          location: {
            name: 'ホテルウエストコート本館',
            lat: 28.382888451824773,
            lng: 129.4938885136643,
            address: '鹿児島県奄美市',
          },
          type: 'restaurant',
        },
        {
          id: 'item-25',
          time: '8:30',
          activity: 'ホテル出発<br>観光 現地車中で相談 土森海岸観光やお土産等',
          note: '',
          checked: false,
          location: {
            name: '土森海岸',
            lat: 28.461420411308595,
            lng: 129.71850655492173,
            address: '鹿児島県奄美市',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-26',
          time: '12:00',
          activity: '昼食 きよら海工房または奄美ブルー',
          note: '',
          checked: false,
          location: {
            name: 'きよら海工房（パン屋）',
            lat: 28.379239685496664,
            lng: 129.49621863297182,
            address: '鹿児島県奄美市',
          },
          website: 'https://kyoraumi.com/pages/asahidori',
          type: 'restaurant',
        },
        {
          id: 'item-27',
          time: '13:10',
          activity: '奄美大島空港へ',
          note: '',
          checked: false,
          location: {
            name: '奄美大島空港',
            lat: 28.4306,
            lng: 129.7128,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-28',
          time: '13:20',
          activity: 'レンタカー返却',
          note: '',
          checked: false,
          location: {
            name: '奄美大島空港',
            lat: 28.4306,
            lng: 129.7128,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'activity',
        },
        {
          id: 'item-29',
          time: '11:40',
          activity: '奄美大島空港発 JAL658便',
          note: 'JAL658便（奄美大島→羽田）11:40→16:25',
          checked: false,
          location: {
            name: '奄美大島空港',
            lat: 28.4306,
            lng: 129.7128,
            address: '鹿児島県大島郡龍郷町',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-30',
          time: '16:25',
          activity: '羽田空港着 お疲れさまでした',
          note: 'JAL658便（奄美大島→羽田）11:40→16:25',
          checked: false,
          location: {
            name: '羽田空港',
            lat: 35.5494,
            lng: 139.7798,
            address: '東京都大田区羽田空港',
          },
          website: 'https://www.haneda-airport.jp/',
          type: 'sightseeing',
        },
        {
          id: 'item-31',
          time: '18:30',
          activity: '池袋駅発 ラビュー',
          note: '',
          checked: false,
          location: {
            name: '池袋駅',
            lat: 35.7295,
            lng: 139.7109,
            address: '東京都豊島区',
          },
          type: 'sightseeing',
        },
        {
          id: 'item-32',
          time: '19:05',
          activity: '入間市駅着',
          note: '',
          checked: false,
          location: {
            name: '入間市駅',
            lat: 35.8372,
            lng: 139.3925,
            address: '埼玉県入間市',
          },
          type: 'sightseeing',
        },
      ],
    },
  ],
  lastUpdated: new Date().toISOString(),
  version: 1,
};

// ツアーコンダクター情報
export const tourConductor = {
  name: '小野敦郎',
  contact: '連絡先',
};

// 持ち物リスト
export const packingList: string[] = [
  'お小遣い（2万円）',
  '2泊なので着替え（不測の事態に備えて多めで）',
  '不要物は持ってこないように',
  '今回、帰りは電車なので大丈夫とは思いますが柔軟に対応できるご準備を',
];

// 反省会情報
export const reflectionMeeting = {
  date: '12月13日（仮）',
  time: '18時',
  location: '新狭山 レストラン ルコッソ イタリアン',
  participants: '全員',
};
